ERROR 2023-05-22 22:15:48,298 log log.py 241 log_response Internal Server Error: /home/add_player_to_team/15818/3918298/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 78, in add_player_to_team
    playerTeam = player_to_drop.roster.first()
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Player' object has no attribute 'roster'
ERROR 2023-05-22 22:18:07,816 log log.py 241 log_response Internal Server Error: /home/add_player_to_team/15818/3918298/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 78, in add_player_to_team
    playerTeam = player_to_drop.starting_teams.roster.first()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyRelatedManager' object has no attribute 'roster'
WARNING 2023-05-23 14:49:46,773 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-05-23 14:50:01,465 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 34, in my_team
    player_points = PlayerDataService.get_player_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 88, in get_player_points
    return PlayerDataService.fetch_and_save_player_stats(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 75, in fetch_and_save_player_stats
    data = PlayerDataService.fetch_player_stats(player_id, week, season)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 38, in fetch_player_stats
    for game in category["events"]:
                ~~~~~~~~^^^^^^^^^^
KeyError: 'events'
WARNING 2023-05-23 21:13:14,687 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-05-24 12:57:07,138 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-05-24 13:05:18,950 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 21, in home
    logger.warning(form.cleaned_data)
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'WeekSelectForm' object has no attribute 'cleaned_data'
ERROR 2023-05-24 13:11:52,658 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 24, in home
    logger.warning(form.cleaned_data)
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'WeekSelectForm' object has no attribute 'cleaned_data'
ERROR 2023-05-24 13:15:17,745 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 20, in home
    form = WeekSelectForm(request.POST or None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\forms.py", line 14, in __init__
    logging.warning("current week in form ", current_week)
                                             ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_week' where it is not associated with a value
ERROR 2023-05-24 13:16:17,908 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 21, in home
    logger.warning("outside post: " + form.data)
                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "MultiValueDict") to str
ERROR 2023-05-24 13:16:34,348 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 32, in home
    logger.warning("week to fetch stats: " + current_week)
                   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
ERROR 2023-05-24 13:17:01,420 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 32, in home
    logger.warning("week to fetch stats: " + current_week)
                   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
ERROR 2023-05-24 13:17:41,643 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 20, in home
    form = WeekSelectForm(request.POST or None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\forms.py", line 18, in __init__
    self.fields["week"].choices = WEEK_CHOICES
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'choices'
ERROR 2023-05-24 13:20:59,697 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 28, in home
    logger.warning(f"week to fetch stats: {current_week}")
                                           ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_week' where it is not associated with a value
ERROR 2023-05-24 13:50:17,006 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 33, in home
    player_points = PlayerDataService.get_player_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 89, in get_player_points
    return PlayerDataService.fetch_and_save_player_stats(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 78, in fetch_and_save_player_stats
    return PlayerDataService.save_player_stats(player_id, week, season, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 71, in save_player_stats
    return float(points, 2)
           ^^^^^^^^^^^^^^^^
TypeError: float expected at most 1 argument, got 2
WARNING 2023-05-25 20:27:48,918 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-05-26 16:03:12,365 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-05-27 15:31:29,041 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-05-29 14:35:44,217 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-05-29 16:07:16,425 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-01 13:44:53,378 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 33, in home
    player_points = PlayerDataService.get_player_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\services.py", line 201, in get_player_points
    player_stat = async_to_sync(PlayerStat.objects.filter)(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 240, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object QuerySet can't be used in 'await' expression
WARNING 2023-06-01 13:44:53,526 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-01 15:16:43,190 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 33, in home
    player_points = DBService.get_player_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 45, in get_player_points
    return APIService.fetch_and_save_player_stats(player.id, week, season)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'APIService' has no attribute 'fetch_and_save_player_stats'
ERROR 2023-06-01 15:22:27,483 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 33, in home
    player_points = DBService.get_player_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 45, in get_player_points
    return DBService.fetch_and_save_player_stats(player.id, week, season)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 50, in fetch_and_save_player_stats
    data = APIService.fetch_player_stats(player_id, week, season)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\api_service.py", line 41, in fetch_player_stats
    raise DBException(
player_scraping.exception_handler.DBException: player data for 16737 does not exist for the week 1
ERROR 2023-06-01 16:09:34,683 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context += DBService.get_player_roster_with_points(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 77, in get_player_roster_with_points
    context["roster_with_points"].append((player, player_points))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'roster_with_points'
ERROR 2023-06-01 16:09:57,378 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context += DBService.get_player_roster_with_points(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 77, in get_player_roster_with_points
    context["roster_with_points"].append((player, player_points))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'append'
ERROR 2023-06-01 16:10:03,091 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context += DBService.get_player_roster_with_points(request)
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'
ERROR 2023-06-01 16:10:29,007 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.get(DBService.get_player_roster_with_points(request))
TypeError: unhashable type: 'dict'
WARNING 2023-06-02 08:20:17,809 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 08:20:30,903 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'WSGIRequest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(request))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 86, in get_weeks_schedule
    matches = Match.objects.filter(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1271, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2057, in get_prep_value
    raise e.__class__(
TypeError: Field 'week' expected a number but got <WSGIRequest: GET '/home/'>.
ERROR 2023-06-02 08:24:33,004 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'WSGIRequest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(request))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 86, in get_weeks_schedule
    matches = Match.objects.filter(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1271, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2057, in get_prep_value
    raise e.__class__(
TypeError: Field 'week' expected a number but got <WSGIRequest: GET '/home/'>.
ERROR 2023-06-02 08:31:23,400 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 17, in home
    context.update(DBService.get_player_roster_with_points(request))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 74, in get_player_roster_with_points
    context["current_week":current_week]
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'slice'
ERROR 2023-06-02 08:31:25,475 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 17, in home
    context.update(DBService.get_player_roster_with_points(request))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 74, in get_player_roster_with_points
    context["current_week":current_week]
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'slice'
WARNING 2023-06-02 08:44:06,495 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 08:48:21,892 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 08:52:01,816 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 08:55:46,204 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 09:00:26,891 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 12:36:41,191 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 12:37:26,507 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\OneDrive\Documents\GitHub\Football-Stats-Web-Scraping\player_scraping\views.py", line 46, in my_team
    return render(request, "my_team.html", {"roster_with_points": roster_with_points})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 18. 
WARNING 2023-06-02 16:18:41,236 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 16:20:16,225 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 27, in my_team
    DBService.propose_transaction()
AttributeError: type object 'DBService' has no attribute 'propose_transaction'
ERROR 2023-06-02 16:20:50,468 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 27, in my_team
    DBService.propose_transaction()
AttributeError: type object 'DBService' has no attribute 'propose_transaction'
ERROR 2023-06-02 16:22:46,150 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 48, in my_team
    return render(request, "my_team.html", {"roster_with_points": roster_with_points})
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 18. 
ERROR 2023-06-02 16:23:32,501 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 49, in my_team
    return render(request, "my_team.html", context=)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trade_player' with no arguments not found. 1 pattern(s) tried: ['home/trade_player/(?P<player_id>[^/]+)/(?P<player_to_drop_id>[^/]+)/\\Z']
ERROR 2023-06-02 16:25:32,890 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 49, in my_team
    return render(request, "my_team.html", context=)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trade_player' with no arguments not found. 1 pattern(s) tried: ['home/trade_player/(?P<player_id>[^/]+)/(?P<player_to_drop_id>[^/]+)/\\Z']
ERROR 2023-06-02 16:25:59,474 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 49, in my_team
    return render(request, "my_team.html", context=)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trade_player' with no arguments not found. 1 pattern(s) tried: ['home/trade_player/(?P<player_id>[^/]+)/(?P<player_to_drop_id>[^/]+)/\\Z']
ERROR 2023-06-02 16:26:52,071 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 49, in my_team
    return render(request, "my_team.html", context=context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trade_player' with no arguments not found. 1 pattern(s) tried: ['home/trade_player/(?P<player_id>[^/]+)/(?P<player_to_drop_id>[^/]+)/\\Z']
ERROR 2023-06-02 16:28:15,113 log log.py 241 log_response Internal Server Error: /home/my_team/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 49, in my_team
    return render(request, "my_team.html", context=context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trade_player' with no arguments not found. 1 pattern(s) tried: ['home/trade_player/(?P<player_id>[^/]+)/(?P<player_to_drop_id>[^/]+)/\\Z']
WARNING 2023-06-02 16:33:05,711 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 16:35:31,439 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 16:36:33,909 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 16:37:09,585 log log.py 241 log_response Not Found: /home/trade_player/
WARNING 2023-06-02 16:37:19,461 log log.py 241 log_response Not Found: /home/trade_player/
WARNING 2023-06-02 16:38:42,601 log log.py 241 log_response Not Found: /home/trade_player/
WARNING 2023-06-02 16:40:21,772 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 16:43:47,554 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 16:44:43,233 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 17:28:54,694 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 17:29:35,027 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 124, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 101, in get_team_points
    for player in team.roster:
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2023-06-02 17:30:04,737 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 124, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 101, in get_team_points
    for player in team.roster.objects.all():
AttributeError: 'ManyRelatedManager' object has no attribute 'objects'
WARNING 2023-06-02 17:30:04,967 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 17:30:42,535 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 124, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 102, in get_team_points
    if not player.points:
AttributeError: 'Player' object has no attribute 'points'
WARNING 2023-06-02 17:30:42,760 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 17:40:38,539 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-06-02 17:40:50,113 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-02 17:41:18,337 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 124, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 102, in get_team_points
    if not player.points:
AttributeError: 'Player' object has no attribute 'points'
ERROR 2023-06-02 17:42:05,804 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 124, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 102, in get_team_points
    if not player.stats.points:
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-02 17:42:54,358 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 127, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 104, in get_team_points
    logger.warning(player.stats.points)
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-02 17:45:43,535 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 125, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player.points
AttributeError: 'Player' object has no attribute 'points'
ERROR 2023-06-02 17:45:57,410 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 125, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player.stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-02 17:46:58,084 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 107, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-02 17:47:16,064 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-02 17:47:28,131 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
WARNING 2023-06-03 08:19:13,806 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-03 08:19:31,402 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:20:13,781 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 127, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 107, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:20:28,532 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 127, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 107, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:21:01,907 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 106, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:21:12,961 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 126, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 94, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 104, in get_team_points
    team_points += DBService.get_player_points(player, week, season)
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
ERROR 2023-06-03 08:22:52,937 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 17, in home
    context.update(DBService.get_player_roster_with_points(request))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 84, in get_player_roster_with_points
    player_points = DBService.get_player_points(
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 47, in get_player_points
    logger.warning(f"Player: {playe}")
NameError: name 'playe' is not defined
ERROR 2023-06-03 08:23:09,803 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 110, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:23:38,453 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 110, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:23:47,794 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 110, in get_team_points
    team_points += player_stats.points
AttributeError: 'RelatedManager' object has no attribute 'points'
ERROR 2023-06-03 08:25:43,430 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 111, in get_team_points
    team_points += player_stat.points
AttributeError: 'QuerySet' object has no attribute 'points'
ERROR 2023-06-03 08:26:28,000 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 109, in get_team_points
    team_points += DBService.get_player_points(player, week, season)
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'
ERROR 2023-06-03 08:26:49,510 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 130, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 111, in get_team_points
    team_points += player_stat.points
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
ERROR 2023-06-03 08:27:59,190 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 133, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 114, in get_team_points
    team_points += player_stat.points
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
WARNING 2023-06-03 08:27:59,472 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-06-03 08:28:17,349 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 18, in home
    context.update(DBService.get_weeks_schedule(context["current_week"]))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 133, in get_weeks_schedule
    DBService.get_match_points(match)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 98, in get_match_points
    match.team1_points = DBService.get_team_points(match.team1, match.week, match.season)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 114, in get_team_points
    team_points += player_stat.points
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
ERROR 2023-06-03 08:31:11,840 log log.py 241 log_response Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jaden\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\views.py", line 17, in home
    context.update(DBService.get_player_roster_with_points(request))
  File "C:\Miscellaneous\Coding Projects\Football-Stats-Web-Scraping\player_scraping\db_service.py", line 82, in get_player_roster_with_points
    context["current_week"] = current_week
NameError: name 'context' is not defined
